Add controllers
RailgunSinon/java-shareit pull request #1
Opened 2023-05-20 13:07 UTC by RailgunSinon

Я из-за майских и болезни тут сильно отстал, так что буду нагонять. Это ТЗ-13, но я в него заложил основу для ТЗ-14, как минимум на уровне архитектуры

2023-05-21 09:53 UTC, Donald522 requested changes
Привет!

Надо немного причесать код, что-то вынести в отдельные классы.

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemController(ItemService itemService, UserService userService) {
Можно заменить на аннотацию RequiredArgsContructor

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (!userService.isUserExists(userId)) {
Я бы эту логику в сервис перенес

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Map<String, String> handleValidationException(final ValidationException exception) {
Это в отдельный класс с аннотацией ControllerAdvice

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static int idCounter = 1;
Генерация id это не ответственность контроллера. 
Лучше перенести это в репозиторий

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private static int idCounter = 1;
Тут тоже самое, лучше перенести генерацию id в репозиторий

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private UserDto convertToDto(User user) {
Конвертацию надо вынести в отдельные классы-конвертеры

2023-05-21 09:53 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +//контроллера предметов
Не понял, как это связано с базой. Можно проверять используя методы репозитория

Да и я не увидел, чтобы у тебя были прямые обращения где-то к мапе users. Я бы убрал static

2023-05-21 09:53 UTC, Donald522 requested changes
Привет!

Надо немного причесать код, что-то вынести в отдельные классы.

2023-05-21 11:09 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +//контроллера предметов
> Не понял, как это связано с базой. Можно проверять используя методы репозитория
> 
> Да и я не увидел, чтобы у тебя были прямые обращения где-то к мапе users. Я бы убрал static

Контроллер предметов запрашивает у юзерсервиса наличие пользователя в хранилище. Сейчас хранилише - мапа, в нее добавляются данные из юзер контроллера, а у него свой юзер сервис. Если я уберу статику юзерсервис в контроллере предметов ничего не будет знать о юерах, которые мы создавали, ибо у них с сервисам из цепочки юзеров разные репозитории. Когда будет БД, этот вопрос решится, так как обращения будут в 1 точку извне, это развяжет руки коду. Но сейчас либо делать статикой весь репозиторий, либо только мапу, что предпочтительнее - меньше статики - меньше головной боли.

2023-05-21 11:13 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private static int idCounter = 1;
> Тут тоже самое, лучше перенести генерацию id в репозиторий

Тут основная проблема была в том, что само ТЗ изначально не предполагает вообще наличие репозитория и сервиса. И я добавил их с забросом на ТЗ14 - там уже работа с БД и вся логика с id и прочее будет удалена за ненадобностью. Но сделаю, не особо проблема

2023-05-21 11:16 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Map<String, String> handleValidationException(final ValidationException exception) {
> Это в отдельный класс с аннотацией ControllerAdvice

Понял, попробую

2023-05-21 11:20 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (!userService.isUserExists(userId)) {
> Я бы эту логику в сервис перенес

Тут очень спорный нюанс, я не вижу смысла конвертировать полученные данные, прокидывать это всё в сервис и там уже понять, что оказывается пользователя то такого нет, и все было зря. Зачастую конвертация данных может быть "тяжелой", а потому я бы заранее отсёк вероятность того, что мы будем это делать. Это от слов предыдущего ревьюера по похожему вопросу  отложилось.   

Но если вопрос принципиален - я переделаю.

2023-05-21 11:20 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemController(ItemService itemService, UserService userService) {
> Можно заменить на аннотацию RequiredArgsContructor

Круто, гляну, спасибо!

2023-05-21 11:35 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static int idCounter = 1;
> Генерация id это не ответственность контроллера. Лучше перенести это в репозиторий

Я знаю, что не его ответственность, но тягать без id объект тяжко, особенно при поиске в конвертере маппера старого объекта. без id будет не очень и нужно будет писать, по=хорошему, два отдельных маппера для создания и для обновления объекта.

2023-05-21 11:51 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Map<String, String> handleValidationException(final ValidationException exception) {
> Это в отдельный класс с аннотацией ControllerAdvice

Я так понимаю, что если ошибку бросит сам контроллера, он ее не перехватит через подобную реализацию. Буду думать как вынести в сервис тогда это дело.

2023-05-21 12:27 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Map<String, String> handleValidationException(final ValidationException exception) {
Отбой, победа. Нужна была не ControllerAdvice, а RestControllerAdvice

2023-05-21 12:47 UTC, RailgunSinon commented
Я поправил всё, кроме твоего замечания по статике. Как дашь твой ответ - будем или править или мержить. Остальное привел к тому виду, как ты хотел, но оставил комменты кое где - интересно услышать твое мнение как разработчика - почему так

2023-05-21 18:59 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        if (!userService.isUserExists(userId)) {
Ну как сказать принципиален. Работать будет и так, конечно. Просто это нарушение single responsibility принципа. Задача контроллера принять запрос. А логику проверки существования пользователя можно вообще в sql запросе сделать.   
Сложность конвертации ничтожно мала по сравнению с походом в БД.
Если конвертация становится "тяжелой" - это явный признак плохой организации кода. Конвертация это перекладывание и ничего более.

2023-05-21 19:02 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public Map<String, String> handleValidationException(final ValidationException exception) {
Если хочешь разные сообщения, то есть 2 варианта.
Либо в конструктор исключения передавать разный текст в каждой из точек выброса, либо сделать базовый класс исключения, от него 2 наследника под кажду сущность, а обработчик на базовый класс. Текст в таком случае можно либо также передавать в конструктор, либо захаркодить в каждом из дочерних классов.

В общем, твои вопросы легко решаются и не являются поводом не использовать механизм, который используется в тысячах проектов и как-то люди живут и им удобно)

2023-05-21 19:04 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static int idCounter = 1;
Вот именно, на следующем шаге id будете генериться в БД. Поэтому нет смысла писать тут этот код сейчас. И интерфейсы придется переделывать. Так что сделай сразу так, что id генерится в репозитории. Такой код будет проще развивать и перейти на другой репозиторий (БД)

2023-05-21 19:05 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    private static int idCounter = 1;
Ты сделал как раз наоборот- без оглядки на будущее ТЗ14. Потому что такой код пришлось бы полностью выбросить и переписать.

2023-05-21 19:07 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +//контроллера предметов
Дергать бд из рандомных мест в коде неверно. Вся работа с БД ведется через класс репозитория, поэтому я и говорю, что тут статика не нужна. Не важна реализация хранилища, важен интерфейс.

2023-05-21 19:12 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +//контроллера предметов
> Дергать бд из рандомных мест в коде неверно. Вся работа с БД ведется через класс репозитория, поэтому я и говорю, что тут статика не нужна. Не важна реализация хранилища, важен интерфейс.

Смотри. У меня юзеры сейчас хранятся в репе юзеров.  А мне нужно из сервиса предметов проверять есть ли юзеры. Я для этого дергаю сервис юзеров. НО так как у нас не БД, каждый новый созданый сервис юзеров работает со своим репозиторием, а следовательно со своей мапой. А потому созданый в сервисе вещей сервис ничего не знает о пользователях, которые созданы в сервисе пользователей. И без статики я этот вопрос никак не решу, если только не буду хранить и предметы и юзеров в общем отдельном классе. Я про это говорю. И статика отпадет сама собой, потому когда я подключу бд, сколько бы я не создавал репозиториев, стучать они будут в 1 БД. Я не знаю как ещё это объяснить.

2023-05-21 19:13 UTC, Donald522 requested changes
Я кажется понял, зачем ты статику делаешь.
И если я правильно понял - то ты не до конца понимаешь как работает спринг в плане создания объектов и нужно разобраться.

2023-05-21 19:13 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/controller/ItemControllerMapper.java
> +public class ItemControllerMapper {
Слово controller в названии лишнее. Просто ItemMapper или ItemConverter

2023-05-21 19:13 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +//контроллера предметов
А что значит, что у UserController и ItemController разные UserService? 
Какого scope-а бины спринг создает по умолчанию?

2023-05-21 19:17 UTC, RailgunSinon commented
> Я кажется понял, зачем ты статику делаешь. И если я правильно понял - то ты не до конца понимаешь как работает спринг в плане создания объектов и нужно разобраться.

Всё, я кажется понял что ты имеешь в виду. Так как у нас не переопределялся scope бина для репозитория - он синглтон, а значит будет 1 на всех и так, без статики. Просто для тебя это очевидно, а я об этом даже не подумал)

2023-05-22 16:20 UTC, Donald522 commented
> > Я кажется понял, зачем ты статику делаешь. И если я правильно понял - то ты не до конца понимаешь как работает спринг в плане создания объектов и нужно разобраться.
> 
> Всё, я кажется понял что ты имеешь в виду. Так как у нас не переопределялся scope бина для репозитория - он синглтон, а значит будет 1 на всех и так, без статики. Просто для тебя это очевидно, а я об этом даже не подумал)

Дело не в том, что для тебя это не очевидно. А в том, что ты стал реализовывать решение, не убедившись в его правоте. Если бы ты написал тест / протестировал вручную, то ты бы увидел, что у тебя все работает и без статики.

Ты раньше случайно не программировал на python?

2023-05-22 16:21 UTC, Donald522 approved these changes
Сейчас все хорошо. Молодец, что разобрался.

2023-05-22 16:21 UTC, Donald522 approved these changes
Сейчас все хорошо. Молодец, что разобрался.

2023-05-22 17:06 UTC, RailgunSinon commented
> > > Я кажется понял, зачем ты статику делаешь. И если я правильно понял - то ты не до конца понимаешь как работает спринг в плане создания объектов и нужно разобраться.
> > 
> > 
> > Всё, я кажется понял что ты имеешь в виду. Так как у нас не переопределялся scope бина для репозитория - он синглтон, а значит будет 1 на всех и так, без статики. Просто для тебя это очевидно, а я об этом даже не подумал)
> 
> Дело не в том, что для тебя это не очевидно. А в том, что ты стал реализовывать решение, не убедившись в его правоте. Если бы ты написал тест / протестировал вручную, то ты бы увидел, что у тебя все работает и без статики.
> 
> Ты раньше случайно не программировал на python?

Я за джаву +- серьезную до курса лет 5 не садился. До этого питон, и местные "локальные" языки от IBM, аналоги фортрана

2023-05-22 17:06 UTC, merged