Add bookings
RailgunSinon/java-shareit pull request #2
Opened 2023-06-03 15:40 UTC by RailgunSinon

ТЗ 14
Заставило сильно посидеть - опыта работы с JPA у меня не так много. На следующей неделе буду ускорять темп и сдавать 15, с моками я хотя бы знаком и там будет полегче. 
На счёт вопроса ранее - да, я раньше работал с питоном много, потом ушел по профилю в джава, но сейчас у меня вся джава совсем олдскульная на работе (зачастую даже не 8 ) и потому я могу косячить в фрейворках особенно.

2023-06-04 20:46 UTC, Donald522 requested changes
Привет!

Все очень неплохо. Оставил немного комментариев.

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                bookingService.getAllBookingOfUserWithState(userId, "ALL"));
RequestParam может принять дефолтное значение параметра

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoInput.java
> +public class BookingDtoInput {
Dto обычно идет суффиксом
Input не очень хорошо звучит, я бы назвал BookingRequest(Dto)

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShort.java
> +public class BookingDtoShort {
Уже не первый раз вижу такое название. Не понимаю почему. Оно не очень неудачное.
Модельные классы - это одно из самых важных в коде проекта. Они задают абстракции, поэтому должны быть легко понятны. Что такое BookingShort?

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByOwnerIdAndStartAfterAndEndBefore(long ownerId,
Мне кажется тут границы надо включать в условии времени

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +//spring название метода, что неудобно и не влезает в норму кол-ва символов в строке.
Это норм.
Вообще, я работал с множеством фреймворков для БД, нет ничего лучше просто сырого sql + jdbcTemplate. Все остальное только мешает.

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Бронь не найдена!");
В ошибку надо добавить id, который мы не нашли

2023-06-04 20:46 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new RuntimeException("Unknown state: UNSUPPORTED_STATUS");
Сюда тоже status надо передать

2023-06-04 20:46 UTC, Donald522 commented on src/main/resources/schema.sql
> +    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
На колонки item_id, booker_id просятся индексы

2023-06-05 13:24 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                bookingService.getAllBookingOfUserWithState(userId, "ALL"));
Круто, сильно упрощает жизнь

2023-06-05 13:31 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShort.java
> +public class BookingDtoShort {
> Уже не первый раз вижу такое название. Не понимаю почему. Оно не очень неудачное. Модельные классы - это одно из самых важных в коде проекта. Они задают абстракции, поэтому должны быть легко понятны. Что такое BookingShort?

Тут сложность в понимании, а как правильно было бы эту сущность обозвать. Это укороченная версия общего ДТО предназначенная конкретно под создания подсущности будущего и прошлого бронирования в запросе получения от владельца. И информативное обзывание этой сущности в стиле BookingShortFormForOwnerRequestDto получается слишком большим для сущности. Обозвать ее как-нибудь Special - не добавляет информативности. Был бы рад идеям, как в таких кейсах называть такие "узконаправленные" сущности, может есть какие-либо правила?

2023-06-05 13:42 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoShort.java
> +public class BookingDtoShort {
Я попробовал сделать так, возможно стало лучше

2023-06-05 13:42 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByOwnerIdAndStartAfterAndEndBefore(long ownerId,
> Мне кажется тут границы надо включать в условии времени

Прочитал - не понял. Перечитал, всё еще не понял :) А Потом как понял :)
Да, скорее всего имеет место быть

2023-06-05 13:54 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new RuntimeException("Unknown state: UNSUPPORTED_STATUS");
> Сюда тоже status надо передать

Вот тут тест, который принимает сообщение об ошибке, строго зашил сообщение в постмане. То есть там строго должна быть такая ошибка или падаем. Я с ней воевал часа полтора и пришлось в итоге зашить это вообще в объект. Первый раз с таким сталкиваюсь =/ Потому не подумал зашил в жесткую .Сейчас переделал на параметр

2023-06-05 19:26 UTC, Donald522 commented on src/main/resources/schema.sql
> +    item_id BIGINT REFERENCES items (id) ON DELETE CASCADE,
Да, они оптимизируют запросы чтения. Но несколько ухудшают запись и потребляют память. Поэтому как и множество решений - это компромисс.

Создаются синтаксисом create index <name> on <table>(column(s))

Материалов масса, можно начать с документации какой-нибудь популярной БД, например postgres
https://www.postgresql.org/docs/current/indexes.html

2023-06-05 19:27 UTC, Donald522 approved these changes

2023-06-05 20:31 UTC, merged