Add item requests
RailgunSinon/java-shareit pull request #3
Opened 2023-06-10 14:36 UTC by RailgunSinon

Постарался охватить насколько меня хватило. Писать тесты на приложение в конце - неблагодарное дело, я больше предпочитаю делать их по ходу или до, но ладно. Времени мало, а потому 100% пока недостижим. Но поправлю, когда буду репы приводить в порядок.

2023-06-12 19:41 UTC, Donald522 requested changes
Привет!

Все нормально, надо немного поправить в паре мест только.

2023-06-12 19:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            .convertToDto(requestService.getItemRequestById(itemRequest.getId(), userId));
А зачем тут потом читать только что созданный объект? Почему метод add не может вернуть все что надо?

2023-06-12 19:41 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/controller/RequestMapper.java
> +        List<Item> items = itemService.getItemsByRequestId(itemRequest.getId());
Ходить из маппера в БД не надо. 
Надо разделять зоны ответственности кода.

2023-06-12 19:41 UTC, Donald522 commented on src/main/resources/schema.sql
> +CREATE INDEX IF NOT EXISTS fki_fk_requests_requester_id ON requests (requester_id ASC NULLS LAST);
Тут разве может быть null?

2023-06-12 19:41 UTC, Donald522 commented on src/main/resources/schema.sql
> +DROP INDEX IF EXISTS fki_fk_requests_requester_id;
Зачем drop?

2023-06-12 19:51 UTC, RailgunSinon commented on src/main/resources/schema.sql
> +DROP INDEX IF EXISTS fki_fk_requests_requester_id;
> Зачем drop?

Я уже писал что не силен в индексах, дропаю их вместе со всей информацией как и вмю остальную

2023-06-12 19:58 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/request/controller/RequestMapper.java
> +        List<Item> items = itemService.getItemsByRequestId(itemRequest.getId());
> Ходить из маппера в БД не надо. Надо разделять зоны ответственности кода.

Попробую перетащить в сервис. Просто это и не работа контроллера, а я маплю в нём. Логичнее показалось разместить это в маппере, чем тащить с собой дальше

2023-06-12 20:00 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            .convertToDto(requestService.getItemRequestById(itemRequest.getId(), userId));
> А зачем тут потом читать только что созданный объект? Почему метод add не может вернуть все что надо?

Тут сделано в единином стиле со всеми контроллерами. Тогда сервис должен возвращать, нужно переделать под эту логику. Для меня функция добавления вообще ничего не должна возвращать, кроме статуса успешно - но тесты решают иначе.

2023-06-12 20:32 UTC, RailgunSinon commented on src/main/java/ru/practicum/shareit/request/controller/RequestMapper.java
> +        List<Item> items = itemService.getItemsByRequestId(itemRequest.getId());
> Ходить из маппера в БД не надо. Надо разделять зоны ответственности кода.

А вообще где в проектах принято мапить - в контроллере или уже в сервисе?

2023-06-12 22:39 UTC, RailgunSinon commented
Избавил маппер от "лишних" функций, заодно перегнал и юзера в сервис (в том же маппере).

2023-06-13 19:58 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +            .convertToDto(requestService.getItemRequestById(itemRequest.getId(), userId));
Ты не прав. Функция добавления должна вернуть хотя бы id.

2023-06-13 19:59 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/controller/RequestMapper.java
> +        List<Item> items = itemService.getItemsByRequestId(itemRequest.getId());
> > Ходить из маппера в БД не надо. Надо разделять зоны ответственности кода.
> 
> А вообще где в проектах принято мапить - в контроллере или уже в сервисе?

Это не принципиально. Где удобнее в конкретном случае.

2023-06-13 20:02 UTC, Donald522 approved these changes

2023-06-13 20:44 UTC, merged