Feat:Попытка теста гитом
RailgunSinon/java-shareit pull request #4
Opened 2023-06-17 17:13 UTC by RailgunSinon

Я пока не понимаю, что с этим докером локально не так. попробую поднять из-под гита

2023-06-17 17:37 UTC, RailgunSinon commented
Короче локально он падает из-за конфликта настроек баз, а тут всё хорошо и все тесты отрабатывают нормально. Как это работает - я не понимаю)

2023-06-18 08:58 UTC, Donald522 requested changes
Привет!

Оставил несколько замечаний

2023-06-18 08:58 UTC, Donald522 commented on DockerfileGateway
> +FROM maven:3.9.2-amazoncorretto-11-debian-bullseye AS builder
эти файлы надо положить в соответствующие модули

2023-06-18 08:58 UTC, Donald522 commented on docker-compose.yml
> +    build:
И вот тут можно написать имя модуля просто

2023-06-18 08:58 UTC, Donald522 commented on docker-compose.yml
> +      - "8081:8081"
Зачем тут 2 порта?

2023-06-18 08:58 UTC, Donald522 commented on docker-compose.yml
> +      - "9091:9091"
Тоже не понимаю зачем 2 порта

2023-06-18 08:58 UTC, Donald522 commented on docker-compose.yml
> +      POSTGRES_USER: root
Лучше создать специального пользователя для приложения, с именем shareit
Под рутом в базу никто не ходит

2023-06-18 08:58 UTC, Donald522 commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data/
А это зачем? Может из-за этого и не запускается локально?

2023-06-18 08:58 UTC, Donald522 commented on server/pom.xml
> +      <artifactId>spring-boot-starter-validation</artifactId>
Эта зависимость в сервере больше не нужна

2023-06-18 08:58 UTC, Donald522 commented on postman/sprint.json
А зачем этот файл коммитится?

2023-06-18 09:51 UTC, RailgunSinon commented on docker-compose.yml
> +      - "8081:8081"
> Зачем тут 2 порта?

Просто хотел посмотреть как будет работать с 2 портами. И в руководстве, что я нашел, была рекомендация использовать 2 порта, мол 2 резервный.

2023-06-18 10:10 UTC, RailgunSinon commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data/
> А это зачем? Может из-за этого и не запускается локально?

Не, тут скорее дело в локальной машине. Я на рабочем ноуте смог таки поднять его. А у меня происходит ошибка
Driver org.h2.Driver claims to not accept jdbcUrl, jdbc:postgresql://db:5432/shareit
То бишь насколько я вижу драйвер от h2 пытается стучать в базу sql, а значит не отработали профили и настройки не сменились. Почему именно домашняя машина себя так ведет - пока непонятно. Но она не чистилась года полтора, и на ней стоит куча стороннего ПО для работы от pgAdmin до IBM Notes и каждый что-то крутит и делает , занимает порты и прочее.

2023-06-18 10:30 UTC, RailgunSinon commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data/
> А это зачем? Может из-за этого и не запускается локально?

Нет, причина не тут.

2023-06-18 10:36 UTC, RailgunSinon commented on docker-compose.yml
> +      - pg-data:/var/lib/postgresql/data/
> А это зачем? Может из-за этого и не запускается локально?

Более того, без этого он взлетать не захотел вообще на гите.

2023-06-18 10:44 UTC, RailgunSinon commented
После правок он вообще умер по итогу =/

2023-06-18 11:16 UTC, RailgunSinon commented
Пришлось хард ресетить. Теперь выясняем что убило.

2023-06-18 11:17 UTC, RailgunSinon commented on server/pom.xml
> +      <artifactId>spring-boot-starter-validation</artifactId>
> Эта зависимость в сервере больше не нужна

Тесты валидации всё еще в сервере. И контроллер сервера также всё ещё валидирует. Было бы время, я бы перенес это все правильно, планирую доделать уже после сдачи, в июле будет отпус и буду приводить в порядок Репозитории. Сейчас если ее убрать падает билд, нужно разносить тесты, убирать валидацию и прочее, а время жмёт уже сильно.

2023-06-18 11:36 UTC, RailgunSinon commented on DockerfileGateway
> +FROM maven:3.9.2-amazoncorretto-11-debian-bullseye AS builder
> эти файлы надо положить в соответствующие модули

попробовал их перенеси с поддержкой idea  - всё упало. Вообще

2023-06-18 11:37 UTC, RailgunSinon commented on postman/sprint.json
Убрал из коммита. Самое безболезненное на сегодня

2023-06-18 11:40 UTC, RailgunSinon commented on docker-compose.yml
> +      POSTGRES_USER: root
> Лучше создать специального пользователя для приложения, с именем shareit Под рутом в базу никто не ходит

Я попробую, но хоть бы где в теории про это было сказано - как это делать.

2023-06-18 12:19 UTC, RailgunSinon commented on DockerfileGateway
> +FROM maven:3.9.2-amazoncorretto-11-debian-bullseye AS builder
> эти файлы надо положить в соответствующие модули
 Я попробовал разные методы - всё падает. Я использую билдер, а ему нужно видеть весь проект, из дочерней директории он туда достучаться не может.
 you cannot include files outside Docker's build context - это то, что нашел в сети, при попытке достучаться вне

2023-06-18 12:27 UTC, RailgunSinon commented on docker-compose.yml
> +    build:
> И вот тут можно написать имя модуля просто

не поправить без замечания 1

2023-06-18 12:31 UTC, RailgunSinon commented on DockerfileGateway
> +FROM maven:3.9.2-amazoncorretto-11-debian-bullseye AS builder
Короче идея в том, что мне на этапе билда мне нужно видеть корневой рут. Если избавиться от билда, можно будет и так сделать. Но решение выглядит менее красивым и правильным, чтоли.

2023-06-18 13:25 UTC, RailgunSinon commented on docker-compose.yml
> +    build:
Переделал 1 - сделал как ты хотел, я думаю

2023-06-18 13:26 UTC, RailgunSinon commented on DockerfileGateway
> +FROM maven:3.9.2-amazoncorretto-11-debian-bullseye AS builder
Но работает лучше кривого билда как не забавно. Даже ожил в итоге локально сервер.

2023-06-18 13:26 UTC, RailgunSinon commented
Короче я убрал сложное композитное собирательство из докера и локально сервер ожил. Видимо проблема была в решении как раз твоего первого комментария, там с доступом из дочерней папки в родительской много пляски. Я упростил максимально решение и оно ожило даже. Но почему было так - я до сих пор не понял, вопрос остаётся открытым.

Забавно, что твое ревью помогло решить проблему, а общение с наставником 2 дня - нет =)

2023-06-19 09:03 UTC, RailgunSinon commented
Я тут с утра решил ещё немного допилить после сдачи уже - я сначала убрал тесты на валидацию, а потом решил, что их лучше было всё же просто перенести и вернул, но на gateway часть, валидация теперь там, вот пусть и тесты там живут.

2023-06-19 18:42 UTC, Donald522 commented
> Короче я убрал сложное композитное собирательство из докера и локально сервер ожил. Видимо проблема была в решении как раз твоего первого комментария, там с доступом из дочерней папки в родительской много пляски. Я упростил максимально решение и оно ожило даже. Но почему было так - я до сих пор не понял, вопрос остаётся открытым.
> 
> Забавно, что твое ревью помогло решить проблему, а общение с наставником 2 дня - нет =)

Надо делать проще. Посмотри принцип KISS.

2023-06-19 18:43 UTC, Donald522 commented
> Такой вопрос возник - а есть генератор подобного шаблона по типу генератора для спринг проектов? Имею в виду многомодульный. Или Нужно руками его создавать?

Не знаю такие

2023-06-19 18:44 UTC, Donald522 approved these changes

2023-06-19 19:05 UTC, merged